### ISSUE TITLE
e2e tests need to be implemented (consolidated issue) 

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#767]
This is consolidating issue to collect all functional e2e tests need to be implemented

- [ ] Test for dynamic logging management #640
- [ ] Test for container auto-scaling to be implemented in #749 
- [x] Cross-site tests inside single cluster #527
- [x] Cross-site tests with multiple clusters (Travis CI only) #995
- [ ] Cross-site and service expose type reflection for #1021
- [ ] Route/Ingress #410
- [ ] Operator upgrade test via migration #658 and simple
- [ ] Custom code deployment (different options, i.e. volumes, jars, maven, etc.) #609
- [ ] More unit-testing
